<?php

use ProcessWire\Module;

class ExternalLinksOpenInNewTab extends Textformatter implements Module {
    public static function getModuleInfo() {
        return [
            'title' => 'Textformatter New tag',
            'version' => 2,
            'summary' => 'Automatically adds target="_blank" to external links.',
            'autoload' => true,
            'singular' => true,
            'href' => 'https://github.com/Matoseb/TextFormatterNewTab'
        ];
    }

    public function format(&$str) {
        $str = preg_replace_callback('/<a\s(.*?)href=["\'](https?:\/\/\S+?)["\'](.*?)>/', function ($matches) {
            $attributes = $matches[1];
            $href = $matches[2];
            $rest = $matches[3];

            // Check if the link is external
            if (strpos($href, wire('config')->httpUrl) !== 0) {
                $attributes .= ' target="_blank"';
            }

            return "<a $attributes href=\"$href\"$rest>";
        }, $str);
    }
}