<?php
class TextFormatterNewTab extends Textformatter {
    public static function getModuleInfo() {
        return [
            'title' => 'Textformatter New tag',
            'version' => 2,
            'summary' => 'Automatically adds target="_blank" to external links.',
            'autoload' => true,
            'singular' => true,
            'href' => 'https://github.com/Matoseb/TextFormatterNewTab'
        ];
    }

    public function format(&$str) {
	    $hosts = wire('config')->httpHosts;
        $str = preg_replace_callback('/<a\s(.*?)href=["\'](https?:\/\/\S+?)["\'](.*?)>/', function ($matches) use ($hosts) {
            $attributes = $matches[1];
            $href = $matches[2];
            $rest = $matches[3];

            // get domain name from href
            $domain = parse_url($href, PHP_URL_HOST);
		  //// compare domain name with allowed hosts
		  if (!in_array($domain, $hosts)) {
                $attributes .= ' target="_blank" rel="noopener noreferrer"';
		  }

            // Check if the link is external
            // if (strpos($href, wire('config')->httpUrl) !== 0) {
            //     $attributes .= ' target="_blank"';
            // }

            return "<a $attributes href=\"$href\"$rest>";
        }, $str);
    }
}